const data = {
  products: [
    {
      _id: '1',
      name: 'Nike dark',
      slug: 'nike-dark',
      category: 'Tshirts',
      image: '/images/p1.jpg',
      price: 50,
      countInStock: 20,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality t-shirt',
    },
    {
      _id: '2',
      name: 'Adidas',
      slug: 'Adidas-white',
      category: 'Tshirts',
      image: '/images/p2.jpg',
      price: 40,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality t-shirt',
    },
    {
      _id: '3',
      name: 'Nike white',
      slug: 'Nike-white',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 50,
      countInStock: 25,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality t-shirt',
    },
    {
      _id: '4',
      name: 'Striped',
      slug: 'Striped-shirt',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 45,
      countInStock: 30,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality t-shirt',
    },
  ],
};

export default data;
