const data = {
  products: [
    {
      name: 'Nike dark t-shirt',
      slug: 'nike-dark-t-shirt',
      category: 'Tshirts',
      image: '/images/p1.jpg',
      price: 50,
      countInStock: 20,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality t-shirt',
    },
    {
      name: 'Adidas t-shirt',
      slug: 'Adidas-t-shirt',
      category: 'Tshirts',
      image: '/images/p2.jpg',
      price: 40,
      countInStock: 60,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality t-shirt',
    },
    {
      name: 'Nike white t-shirt',
      slug: 'Nike-white-t-shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 50,
      countInStock: 25,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality t-shirt',
    },
    {
      name: 'Striped t-shirt',
      slug: 'Striped-t-shirt',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 45,
      countInStock: 30,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality t-shirt',
    },
  ],
};

export default data;
